    language: python

    python:
      - "3.3"
      - "3.4"
      - "3.5"
      - "3.6"

    env:
      -DJANGO=1.11.6 DB=sqlite

    install:
      - pip install -r WebPyRobot/requirements.txt

    script:
      - python WebPyRobot/manage.py test backend.tests.SimpleTest.test_details

